### ISSUE TITLE
Support Ubuntu Xenial

### ISSUE THREAD

**Issue by Andrey-mp** [juju-solutions/charm-mysql#5]
Are you planned to support xenial version of Ubuntu?
Regards,
Andrey.

**Comment by marcoceppi** [comment]
We are planning, but we're moving to a layered charm for Xenial. I expect we'll have something for review in 2 weeks time.

**Comment by zioproto** [comment]
Hello @marcoceppi 
is the mysql charm supposed to work on Xenial ?

I am trying the Getting started guide for juju that uses the mysql charm:
https://jujucharms.com/docs/devel/getting-started

The mysql app goes always in error. Can you confirm this is supposed to work on Ubuntu Xenial ? thank you

```
ubuntu@xenial:~$ juju status --format=yaml
model:
  name: default
  controller: lxd-test
  cloud: localhost
  region: localhost
  version: 2.0.3
machines:
  "0":
    juju-status:
      current: started
      since: 19 Feb 2017 10:02:59+01:00
      version: 2.0.3
    dns-name: 10.16.172.119
    ip-addresses:
    - 10.16.172.119
    instance-id: juju-a1130f-0
    machine-status:
      current: running
      message: Running
      since: 19 Feb 2017 10:02:32+01:00
    series: trusty
    hardware: arch=amd64 cores=0 mem=0M
  "1":
    juju-status:
      current: started
      since: 19 Feb 2017 10:03:05+01:00
      version: 2.0.3
    dns-name: 10.16.172.91
    ip-addresses:
    - 10.16.172.91
    instance-id: juju-a1130f-1
    machine-status:
      current: running
      message: Running
      since: 19 Feb 2017 10:02:43+01:00
    series: trusty
    hardware: arch=amd64 cores=0 mem=0M
applications:
  mediawiki:
    charm: cs:trusty/mediawiki-3
    series: trusty
    os: ubuntu
    charm-origin: jujucharms
    charm-name: mediawiki
    charm-rev: 3
    exposed: false
    application-status:
      current: unknown
      since: 19 Feb 2017 10:05:17+01:00
    relations:
      db:
      - mysql
    units:
      mediawiki/0:
        workload-status:
          current: unknown
          since: 19 Feb 2017 10:05:17+01:00
        juju-status:
          current: idle
          since: 19 Feb 2017 10:05:17+01:00
          version: 2.0.3
        leader: true
        machine: "0"
        public-address: 10.16.172.119
  mysql:
    charm: cs:trusty/mysql-29
    series: trusty
    os: ubuntu
    charm-origin: jujucharms
    charm-name: mysql
    charm-rev: 29
    exposed: false
    application-status:
      current: error
      message: 'hook failed: "start"'
      since: 19 Feb 2017 10:05:51+01:00
    relations:
      cluster:
      - mysql
      db:
      - mediawiki
    units:
      mysql/0:
        workload-status:
          current: error
          message: 'hook failed: "start"'
          since: 19 Feb 2017 10:05:51+01:00
        juju-status:
          current: idle
          since: 19 Feb 2017 10:05:51+01:00
          version: 2.0.3
        leader: true
        machine: "1"
        public-address: 10.16.172.91
```
